# Generated by Django 3.1.4 on 2021-01-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка категории')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание категории')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(blank=True, null=True)),
                ('rgt', models.PositiveIntegerField(blank=True, null=True)),
                ('depth', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=11, null=True)),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Активная ли категория')),
                ('is_custom', models.BooleanField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Название родительской категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название школы')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на школу')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/school/logo', verbose_name='Лого школы')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'db_table': 'scholl',
            },
        ),
        migrations.CreateModel(
            name='CoursePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнерская ссылка')),
                ('create_at', models.DateTimeField(verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(verbose_name='Дата последнего изменения')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_category', to='courses.coursecategory', verbose_name='Отношение к категории')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'course_partner',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('slug', models.URLField(blank=True, null=True, verbose_name='Ссылка на курс')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала курса')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания курса')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Дата окончания курса')),
                ('installment', models.BooleanField(default=False, verbose_name='Есть ли рассрочка платежа')),
                ('raiting', models.PositiveIntegerField(default=0, verbose_name='Есть ли рассрочка платежа')),
                ('create_at', models.DateTimeField(verbose_name='Дата создания курса')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='courses.coursecategory', verbose_name='Категория курса')),
                ('school_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_school', to='courses.school', verbose_name='Онлайн школа курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
            },
        ),
    ]
