# Generated by Django 3.0.6 on 2021-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210114_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название школы'),
        ),
    ]
