# Generated by Django 3.0.6 on 2021-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210114_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Ссылка на школу(внутренняя)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на школу(внешняя)'),
        ),
    ]
