# Generated by Django 3.0.6 on 2021-02-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210114_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='discription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.CourseCategory', verbose_name='Название родительской категории'),
        ),
    ]
