# Generated by Django 3.0.6 on 2021-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210217_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='partner_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнерская ссылка'),
        ),
        migrations.DeleteModel(
            name='CoursePartner',
        ),
    ]
