# Generated by Django 3.0.6 on 2021-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка на новость')),
                ('date_published', models.DateTimeField(verbose_name='Дата публикации')),
                ('description', models.CharField(max_length=500, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['date_published'],
            },
        ),
    ]
